feat: add force revocable parameter to token endpoints
jfrog/vault-plugin-secrets-artifactory pull request #175
Opened 2024-04-17 00:11 UTC by georgeskill

Hello.  I went ahead and added the `force_revocable` parameter as an optional parameter.  By default, `use_expiring_tokens` will still set `force_revocable` to `true`, unless it is explicitly given.  This should solve my issue at #174.  My access tokens metadata indicated they were not revocable, but also had a value in `expires_in`.

"I have read the CLA Document and I hereby sign the CLA"

2024-04-17 00:11 UTC, georgeskill commented
"I have read the CLA Document and I hereby sign the CLA"

2024-04-17 09:54 UTC, gr-david-snowdon commented
recheck

2024-04-17 13:40 UTC, georgeskill commented
recheck

2024-04-17 16:58 UTC, alexhung commented
recheck

2024-04-17 17:04 UTC, alexhung requested changes
The API request payload needs to use this new config value. See https://github.com/jfrog/vault-plugin-secrets-artifactory/blob/master/artifactory.go#L149

2024-04-17 17:04 UTC, alexhung commented on path_config.go
> +
Let's have consistent style, so please remove these empty lines 😄

2024-04-18 03:09 UTC, ApolloGie commented
> The API request payload needs to use this new config value. See https://github.com/jfrog/vault-plugin-secrets-artifactory/blob/master/artifactory.go#L149

Can you elaborate please?  I am setting the request's ForceRevocable value to the config's value if it's present.

2024-04-18 03:19 UTC, georgeskill commented
> The API request payload needs to use this new config value. See https://github.com/jfrog/vault-plugin-secrets-artifactory/blob/master/artifactory.go#L149

Can you elaborate please? I am setting the request's ForceRevocable value to the config's value if it's not null.

2024-04-18 16:05 UTC, alexhung commented
@georgeskill You're right, you did! I missed it during review.

2024-04-18 16:06 UTC, alexhung approved these changes

2024-04-18 18:06 UTC, georgeskill commented
> @georgeskill You're right, you did! I missed it during review.

Thanks for approving.  How can I get the CLA Assistant action to pass?  Am I missing a step to get it to pass?

2024-04-18 18:46 UTC, alexhung commented
@georgeskill If you wish to try to sign CLA again, please include only the CLA message. I think the last time you also included the 'rechecking' and that confused the GitHub Action.

2024-04-18 19:44 UTC, georgeskill commented
I have read the CLA Document and I hereby sign the CLA

2024-04-18 19:44 UTC, georgeskill commented
recheck

2024-04-18 19:49 UTC, alexhung commented
@georgeskill Don't worry about CLA GitHub Action. You clearly have signed it 😄

2024-04-18 21:44 UTC, merged